# DB
spring.datasource.url=jdbc:postgresql://postgres:5432/stodb
spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.username=postgres
spring.datasource.password=qorhqtlrp

spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

spring.h2.console.enabled=false

spring.data.redis.host=redis
spring.data.redis.port=6379
